import type { Metadata } from 'next'
import './globals.css'
import { gilroy } from '@/public/fonts/gilroy'
import { Navbar } from '@/components/navbar'
import { GlobalScrollBar } from '@/components/global-scrollbar'
import { MenuContextProvider } from '@/contexts/menu-context'
import { Menu } from '@/components/menu'

export const metadata: Metadata = {
  title: 'Elias Souza — Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${gilroy.variable} text-paragraph font-gilroy bg-black`}
      >
        <MenuContextProvider>
          <Navbar />
          <Menu />
          {children}
          <GlobalScrollBar />
        </MenuContextProvider>
      </body>
    </html>
  )
}
